services:
  app:
    container_name: chat-app-backend-app
    build:
      context: ./app/
      dockerfile: Dockerfile
      args:
        LOCAL_UID: ${LOCAL_UID}
        LOCAL_GID: ${LOCAL_GID}
      target: local
    tty: true
    ports:
      - "3000:3000"
      - "5555:5555"
      - "9229:9229"
    volumes:
      - ./app:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.1
    container_name: chat-app-backend-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auT*k!K9Tp(8
      POSTGRES_DB: chat-app-db
    restart: always

volumes:
  node-modules:
